apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec: 
      progressDeadlineSeconds: 1800
      containers:
        - name: {{ .Values.serviceName }}
          image: aespicaacrqa.azurecr.io/app-hello:latest
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 8099
  selector:
    app: {{ .Values.serviceName }}
