apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: {{ .Values.serviceName }}
          image: aespicaacrqa.azurecr.io/app-hello:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8090
          env:
            - name: TITLE
              value: {{ .Values.title }}
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 9376
  type: LoadBalancer
